import PlaceholderImg from '../../assets/images/placeholder_img.png';

export const rawPowerData = [
  {
    cover: PlaceholderImg,
    actionPower: 'Soco/Chute',
    skill: 'Briga',
    level: 'N/A',
    test: 'Força ou Destreza + Briga',
    difSugest: '1 (alvo parado) / 2+ (alvo em movimento)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Acerta um ataque corpo a corpo desarmado. A Margem de Sucesso aumenta o dano. Causa Dano Superficial.',
    clans: 'Todos',
    counterResist:
      'Destreza + Esportes (Esquivar); Vigor + Briga (Bloquear/Aparar)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Soco/Chute Aprimorado (Punho de Ferro)',
    skill: 'Potência',
    level: 1,
    test: 'Força ou Destreza + Briga',
    difSugest: '1 (alvo parado) / 2+ (alvo em movimento)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Seus ataques desarmados (socos/chutes) passam a causar Dano Agravado em vez de Superficial. A Margem de Sucesso do teste de ataque ainda aumenta o dano.',
    clans: 'Brujah, Lasombra',
    counterResist: 'Fortitude (reduz Dano Agravado)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Agarrar/Imobilizar',
    skill: 'Briga',
    level: 'N/A',
    test: 'Força + Briga',
    difSugest: '2 (alvo desprevenido) / 3+ (alvo ciente)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Agarra ou imobiliza um alvo. A Margem de Sucesso determina a força do aperto ou a dificuldade de escapar. Alvo fica Agarrado ou Imobilizado.',
    clans: 'Todos',
    counterResist:
      'Força + Briga (escapar); Destreza + Esportes (desvencilhar); Gasto de FV (sucesso automático na tentativa de escape)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Empurrar/Derrubar',
    skill: 'Briga ou Esportes',
    level: 'N/A',
    test: 'Força + Briga ou Esportes',
    difSugest: '2 (alvo desprevenido) / 3+ (alvo equilibrado)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Empurra ou derruba um alvo, fazendo-o ficar Caído.',
    clans: 'Todos',
    counterResist:
      'Destreza + Esportes (manter o equilíbrio); Vigor + Esportes (resistir ao empurrão)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Atirar (Pistola/Rifle)',
    skill: 'Armas de Fogo',
    level: 'N/A',
    test: 'Destreza + Armas de Fogo',
    difSugest:
      '2 (alvo parado a curta distância) / 4 (alvo em movimento/média) / 6+ (longa/difícil)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Acerta um alvo com arma de fogo. A Margem de Sucesso aumenta o dano da arma. Causa Dano Superficial (a menos que a arma seja inerentemente Agravada).',
    clans: 'Todos',
    counterResist:
      'Destreza + Esportes (Esquivar); Vigor + Esportes (Abrigo/Cover); Fortitude (reduz dano)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Atirar (Arco/Zarabatana)',
    skill: 'Pontaria',
    level: 'N/A',
    test: 'Destreza + Pontaria',
    difSugest:
      '2 (alvo parado) / 4 (vento/distância) / 6+ (alvo em movimento/difícil)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Acerta um alvo com um projétil de arco ou zarabatana. A Margem de Sucesso aumenta o dano. Causa Dano Superficial (ou Agravado se for seta mágica/venenosa).',
    clans: 'Todos',
    counterResist:
      'Destreza + Esportes (Esquivar); Vigor + Esportes (Abrigo/Cover); Fortitude (reduz dano)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Ataque com Armas Brancas (Faca/Espada/Machado)',
    skill: 'Armas Brancas',
    level: 'N/A',
    test: 'Destreza + Armas Brancas',
    difSugest: '1 (alvo parado) / 2+ (alvo em movimento)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Acerta um alvo com uma arma branca. A Margem de Sucesso aumenta o dano da arma. Causa Dano Superficial (ou Agravado se arma especial/Disciplina).',
    clans: 'Todos',
    counterResist:
      'Destreza + Esportes (Esquivar); Destreza + Armas Brancas (Parar/Bloquear com arma)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Ataque com Armas de Contusão (Taco/Tijolo/Martelo)',
    skill: 'Armas Brancas',
    level: 'N/A',
    test: 'Força + Armas Brancas',
    difSugest: '1 (alvo parado) / 2+ (alvo em movimento)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Acerta um alvo com uma arma de contusão. A Margem de Sucesso aumenta o dano da arma. Causa Dano Superficial.',
    clans: 'Todos',
    counterResist:
      'Destreza + Esportes (Esquivar); Vigor + Briga (Aparar/Bloquear)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Ataque com Serra Elétrica',
    skill: 'Ofícios (ou Armas Brancas)',
    level: 'N/A',
    test: 'Força + Ofícios (ou Armas Brancas)',
    difSugest: '3 (difícil de manobrar) / 4+ (alvo em movimento)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Acerta um alvo com uma serra elétrica. A Margem de Sucesso aumenta o dano. **Causa Dano Agravado**.',
    clans: 'Todos',
    counterResist: 'Destreza + Esportes (Esquivar); Fortitude (reduz dano)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Escalar Superfície Vertical',
    skill: 'Esportes',
    level: 'N/A',
    test: 'Destreza + Esportes',
    difSugest:
      '2 (terreno fácil) / 4 (parede lisa) / 6 (parede molhada, sem apoio)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Progride na escalada. A Margem de Sucesso indica a velocidade da escalada.',
    clans: 'Todos',
    counterResist: 'N/A (ação de deslocamento)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Saltar Grandes Distâncias',
    skill: 'Esportes',
    level: 'N/A',
    test: 'Força ou Destreza + Esportes',
    difSugest: '2 (obstáculo baixo) / 4 (fenda larga) / 6 (prédio para prédio)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Consegue o salto. A Margem de Sucesso indica elegância/precisão.',
    clans: 'Todos',
    counterResist: 'N/A (ação de deslocamento)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Saltar Longe/Alto (Potência)',
    skill: 'Potência',
    level: 2,
    test: 'Força + Esportes',
    difSugest: '2-4 (depende da distância/altura)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Realiza saltos extraordinários, cobrindo grandes distâncias ou alturas.',
    clans: 'Brujah, Lasombra',
    counterResist: 'N/A (ação de movimento)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Correr em Velocidade Extrema (Dash)',
    skill: 'Rapidez',
    level: 1,
    test: 'N/A (ativado por gasto de PB)',
    difSugest: 'N/A',
    costs: '1 PB',
    bloodPotency: 'N/A',
    description:
      'Aumenta sua velocidade de movimento em um turno (sua Destreza + 10m por nível de Rapidez). Pode conceder ações extras em níveis superiores.',
    clans: 'Brujah, Banu Haqim, Toreador',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Quebrar Objeto (Força Bruta)',
    skill: 'Esportes',
    level: 'N/A',
    test: 'Força + Esportes',
    difSugest: '2 (porta fraca) / 4 (parede fina) / 6 (porta blindada)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Quebra ou abre o objeto. A Margem de Sucesso indica rapidez e eficácia.',
    clans: 'Todos',
    counterResist: 'Dificuldade da estrutura do objeto',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Agir Furtivamente/Esconder-se',
    skill: 'Furtividade',
    level: 'N/A',
    test: 'Destreza + Furtividade',
    difSugest:
      '2 (pouca gente) / 4 (multidão barulhenta) / 6 (silêncio total, sem cobertura)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Passa despercebido ou se esconde.',
    clans: 'Todos',
    counterResist:
      'Raciocínio + Prontidão (Notar alvo); Raciocínio + Investigação (Procurar pistas); Auspícios (percepção sobrenatural)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Arrombar Fechadura (Prédio/Carro)',
    skill: 'Segurança',
    level: 'N/A',
    test: 'Destreza + Segurança',
    difSugest:
      '2 (simples) / 4 (padrão) / 6 (complexa/digital) / 8+ (cofre/segurança bancária)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Abre a fechadura ou sistema. A Margem de Sucesso indica rapidez e discrição.',
    clans: 'Todos',
    counterResist:
      'Inteligência + Segurança (alarmes/câmeras); Inteligência + Tecnologia (sistemas digitais)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Pilotar Moto/Veículo Esportivo',
    skill: 'Condução',
    level: 'N/A',
    test: 'Destreza + Condução',
    difSugest:
      '2 (normal) / 4 (alta velocidade/tráfego) / 6+ (perseguição/manobras perigosas)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Mantém o controle e progride. A Margem de Sucesso indica velocidade e manobrabilidade.',
    clans: 'Todos',
    counterResist:
      'Destreza + Condução (em perseguição para seguir/bloquear); Raciocínio + Prontidão (prever manobras)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Resistência Passiva a Dano',
    skill: 'Fortitude',
    level: 1,
    test: 'N/A (passivo)',
    difSugest: 'N/A',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Reduz passivamente o Dano Superficial sofrido.',
    clans: 'Gangrel, Ventrue, Hecata',
    counterResist: 'Ataques de Dano Agravado',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Resistência a Dano (Resiliência)',
    skill: 'Fortitude',
    level: 1,
    test: 'N/A (gasto para efeito)',
    difSugest: 'N/A',
    costs: '1 PB',
    bloodPotency: 'N/A',
    description: 'Converte 1 ponto de Dano Agravado sofrido em Superficial.',
    clans: 'Gangrel, Ventrue, Hecata',
    counterResist:
      'Ataques que causam Dano Agravado massivo e superior à sua Fortitude',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Corpo Indestrutível',
    skill: 'Fortitude',
    level: 5,
    test: 'N/A (passivo)',
    difSugest: 'N/A',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Imunidade a dano físico mundano.',
    clans: 'Gangrel, Ventrue',
    counterResist: 'Ataques de Poderes Sobrenaturais / Dano Agravado Extremo',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Ataque com Garras/Presas (Armas Ferais)',
    skill: 'Metamorfose',
    level: 1,
    test: 'Força ou Destreza + Briga',
    difSugest: '1 (alvo parado) / 2+ (alvo em movimento)',
    costs: '1 PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Cria garras afiadas e presas que causam **Dano Agravado** em ataques desarmados.',
    clans: 'Gangrel, Ministry',
    counterResist: 'Ataques à distância; Fortitude (reduz dano)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Pele de Pedra',
    skill: 'Metamorfose',
    level: 2,
    test: 'N/A (passivo)',
    difSugest: 'N/A',
    costs: '1 PB',
    bloodPotency: 'N/A',
    description:
      'Endurece a pele, permitindo absorver uma quantidade de Dano Superficial igual ao seu nível de Metamorfose por turno.',
    clans: 'Gangrel, Ministry',
    counterResist:
      'Ataques que causam Dano Agravado ignoram essa redução de dano',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Transformação em Animal (Forma da Besta)',
    skill: 'Metamorfose',
    level: 3,
    test: 'N/A (ativado)',
    difSugest: 'N/A',
    costs: '2 PB',
    bloodPotency: 'N/A',
    description:
      'Transforma o vampiro em um animal predador (lobo, morcego, etc.), ganhando seus atributos físicos e habilidades.',
    clans: 'Gangrel, Ministry',
    counterResist: 'Armas de fogo; ataques de área',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Moldar Ossos',
    skill: 'Metamorfose',
    level: 4,
    test: 'Vigor + Metamorfose',
    difSugest: '2 (pequenas mudanças) / 4 (grandes mudanças)',
    costs: '1+ PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Altera a estrutura óssea ou muscular do próprio corpo ou de outros, criando espinhos, endurecendo a pele, etc.',
    clans: 'Gangrel',
    counterResist:
      'Ataques que forçam a mudança de forma; magia que impede transformações',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Corpo Elemental',
    skill: 'Metamorfose',
    level: 5,
    test: 'N/A (ativado)',
    difSugest: 'N/A',
    costs: '3 PB',
    bloodPotency: 'N/A',
    description:
      'Transforma-se em névoa, terra ou chamas, ganhando imunidades e a capacidade de passar por pequenas aberturas.',
    clans: 'Gangrel',
    counterResist:
      'Depende da forma (ex: água para chamas, vento forte para névoa)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Manto de Sombras',
    skill: 'Ofuscação',
    level: 1,
    test: 'Destreza + Furtividade',
    difSugest:
      '2 (iluminação baixa) / 4 (iluminação normal) / 6+ (área bem iluminada)',
    costs: '1 PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Permite que o vampiro se misture às sombras e se torne quase invisível para observadores mundanos, adicionando dados à sua rolagem de Furtividade.',
    clans: 'Nosferatu, Banu Haqim',
    counterResist:
      'Auspícios (pode ver através); sensores tecnológicos; Raciocínio + Prontidão (notar pequenas perturbações); luz solar/fogo',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Invisibilidade Total',
    skill: 'Ofuscação',
    level: 3,
    test: 'N/A (ativado)',
    difSugest: 'N/A',
    costs: '1 PB',
    bloodPotency: 'N/A',
    description:
      'Torna o vampiro completamente invisível a olhos mundanos. Mantém a invisibilidade a menos que se envolva em combate ou chame muita atenção.',
    clans: 'Nosferatu, Banu Haqim',
    counterResist:
      'Auspícios (pode ver através); sensores tecnológicos específicos',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Awe (Fascinar Multidão/Alvo)',
    skill: 'Presença',
    level: 1,
    test: 'Carisma + Presença',
    difSugest: '1 (simples) / 3 (forte) / 5 (em combate)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Os humanos (e alguns outros) ficam fascinados pelo vampiro, dificultando que o ignorem ou ajam contra ele.',
    clans: 'Toreador, Ventrue, Ministry',
    counterResist:
      'Autocontrole + Determinação (resistir à atração); Gasto de FV (superar por uma cena)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Dread Gaze (Causar Medo Intenso)',
    skill: 'Presença',
    level: 2,
    test: 'Carisma + Intimidação',
    difSugest: '2 (pequeno) / 4 (forte) / 6 (paralisante)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Causa pânico ou terror no alvo através do olhar, levando-o a fugir ou ficar paralisado de medo.',
    clans: 'Toreador, Ventrue, Ministry',
    counterResist:
      'Autocontrole + Vigor (resistir ao pânico); Gasto de FV (superar)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Majesty (Comandar Lealdade de Muitos)',
    skill: 'Presença',
    level: 4,
    test: 'Carisma + Liderança',
    difSugest: '4 (pequeno grupo) / 6 (grande grupo) / 8 (multidão)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Inspira lealdade e devoção em um grupo de pessoas, tornando-as suscetíveis à sua vontade.',
    clans: 'Toreador, Ventrue, Ministry',
    counterResist:
      'Força de Vontade (resistência individual); presença de líderes opostos',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Obtenebration (Manto de Sombras)',
    skill: 'Obtenebration',
    level: 1,
    test: 'Manipulação + Obtenebration',
    difSugest: '1-3 (depende da densidade desejada)',
    costs: '1 PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Manifesta sombras para criar escuridão densa, cobrir-se ou objetos.',
    clans: 'Lasombra',
    counterResist:
      'Fontes de luz intensas (fogo, luz solar); Auspícios (pode ver através da escuridão mágica)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Braços do Abismo',
    skill: 'Obtenebration',
    level: 2,
    test: 'Força + Obtenebration',
    difSugest: 'Varia (alvo parado/movimento, se manipular objetos)',
    costs: '1 PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Manifesta tentáculos de sombra do solo para atacar ou manipular objetos. Causa Dano Agravado em combate.',
    clans: 'Lasombra',
    counterResist:
      'Destreza + Esportes (esquivar); ataques que dispersem a sombra',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Corredor do Abismo',
    skill: 'Obtenebration',
    level: 3,
    test: 'N/A (ativado)',
    difSugest: 'N/A',
    costs: '1 PB',
    bloodPotency: 'N/A',
    description:
      'Cria uma fenda de sombra que permite ao vampiro viajar rapidamente para outro local dentro da linha de visão.',
    clans: 'Lasombra',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Forma da Noite',
    skill: 'Obtenebration',
    level: 4,
    test: 'N/A (ativado)',
    difSugest: 'N/A',
    costs: '2 PB',
    bloodPotency: 'N/A',
    description:
      'Transforma-se em uma nuvem de sombra gigante, ganhando resistência a dano físico e capacidade de voo.',
    clans: 'Lasombra',
    counterResist: 'Luz intensa; ataques de área',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Invocar o Oblivion',
    skill: 'Obtenebration',
    level: 5,
    test: 'Manipulação + Obtenebration',
    difSugest: '3-5 (depende da criatura/efeito)',
    costs: '3+ PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Invoca uma entidade pura de Oblivion (ex: Cão de Sombra) para auxiliar o vampiro.',
    clans: 'Lasombra',
    counterResist: 'Luz intensa; ataques agravados; ataques de área de efeito',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Toque do Terrível',
    skill: 'Oblivion',
    level: 1,
    test: 'Manipulação + Oblivion',
    difSugest: '2-4',
    costs: '1 PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Causa terror irracional no alvo através do toque ou proximidade.',
    clans: 'Hecata',
    counterResist:
      'Força de Vontade (resistir); Vigor + Determinação (superar o medo)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Corpo de Sombras',
    skill: 'Oblivion',
    level: 3,
    test: 'Vigor + Oblivion',
    difSugest: '1-3',
    costs: '1 PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Transforma o corpo em uma forma sombria e etérea, concedendo resistência a dano físico e permitindo passar por pequenas aberturas.',
    clans: 'Hecata',
    counterResist:
      'Luz intensa; ataques de Feitiçaria de Sangue/Auspícios que afetam a essência',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Invocar a Noite',
    skill: 'Oblivion',
    level: 5,
    test: 'Raciocínio + Oblivion',
    difSugest: '4-6',
    costs: 'Gasto de PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Cria uma área de escuridão sobrenatural impenetrável que dissipa luzes mundanas.',
    clans: 'Hecata',
    counterResist: 'Poderes de luz sobrenaturais; evitar a área de efeito',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Rito do Sangue de Diablerie',
    skill: 'Feitiçaria de Sangue',
    level: 1,
    test: 'Raciocínio + Feitiçaria de Sangue',
    difSugest: '1-3',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Detecta se alguém consumiu sangue de outro vampiro.',
    clans: 'Tremere, Banu Haqim, Hecata',
    counterResist: 'N/A (ação de detecção)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Sanguinar',
    skill: 'Feitiçaria de Sangue',
    level: 2,
    test: 'Raciocínio + Feitiçaria de Sangue',
    difSugest: 'vs. Vigor + Determinação',
    costs: '1 PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Causa dor e dano ao alvo através do sangue.',
    clans: 'Tremere, Banu Haqim',
    counterResist: 'Vigor + Determinação (resistir)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Evocar o Morto',
    skill: 'Ocultismo',
    level: 2,
    test: 'Raciocínio + Ocultismo',
    difSugest: '2-4',
    costs: '1 PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Invoca um espírito para interagir ou fazer perguntas (para Hecata e outros com rituais de Necromancia).',
    clans: 'Hecata',
    counterResist:
      'Outros poderes espirituais; afastar o espírito com fé/ritual',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Alma Flamejante',
    skill: 'Feitiçaria de Sangue',
    level: 3,
    test: 'Raciocínio + Feitiçaria de Sangue',
    difSugest: '3-5',
    costs: '1 PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Conjura chamas de sangue que causam Dano Agravado.',
    clans: 'Tremere, Banu Haqim',
    counterResist:
      'Vigor + Determinação (resistir ao dano); Fortitude (reduzir)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'O Coração do Desespero',
    skill: 'Feitiçaria de Sangue',
    level: 4,
    test: 'Raciocínio + Feitiçaria de Sangue',
    difSugest: 'vs. Vigor + Determinação',
    costs: '1 PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Causa hemorragia interna severa no alvo.',
    clans: 'Tremere, Banu Haqim',
    counterResist: 'Vigor + Determinação (resistir)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Maldição do Sangue',
    skill: 'Feitiçaria de Sangue',
    level: 5,
    test: 'Raciocínio + Feitiçaria de Sangue',
    difSugest: '6+',
    costs: 'Gasto de PB',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Cria uma maldição de longo prazo no alvo.',
    clans: 'Tremere, Banu Haqim',
    counterResist:
      'Magia de remoção de maldições; superar com Força de Vontade',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Domar uma Fera (sem Animalismo)',
    skill: 'Empatia ou Liderança',
    level: 'N/A',
    test: 'Carisma + Empatia ou Liderança',
    difSugest:
      '4 (animal selvagem) / 6 (predador) / 8 (animal treinado e agressivo)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Acalma ou controla um animal. A Margem de Sucesso indica o nível de obediência.',
    clans: 'Todos',
    counterResist: 'Resistência é a natureza e ferocidade do animal',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Criar Ghouls / Laços de Sangue',
    skill: 'Liderança (para Ghouls voluntários)',
    level: 'N/A',
    test: 'Nenhum teste direto para Laço de Sangue (é uma mecânica de 3 beijos em 3 noites diferentes)',
    difSugest: 'N/A',
    costs: 'Gasto de PB e tempo',
    bloodPotency: 'N/A',
    description:
      'Ghoul: Cria um servo mortal com alguns poderes vampíricos e lealdade forçada. Laço de Sangue: Cria lealdade e fascínio obsessivo em qualquer um que beije seu sangue 3 vezes.',
    clans: 'Todos',
    counterResist:
      'Romper o laço (longo e difícil); matar o vampiro que criou o laço; Disciplinas mentais para quebrar a lealdade',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Consertar Objeto / Dispositivo',
    skill: 'Ofícios ou Tecnologia',
    level: 'N/A',
    test: 'Inteligência + Ofícios ou Tecnologia',
    difSugest: '2 (simples) / 4 (moderado) / 6 (complexo)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Realiza um reparo. 1 Sucesso: Reparo parcial. Margem de Sucesso: Reparo completo/eficaz.',
    clans: 'Todos',
    counterResist: 'N/A (ação de reparo)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Cozinhar/Preparar Refeição',
    skill: 'Ofícios',
    level: 'N/A',
    test: 'Inteligência ou Raciocínio + Ofícios',
    difSugest: '1 (básica) / 3 (gourmet) / 5 (exótica/ritualística)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Prepara uma refeição. 1 Sucesso: Refeição pronta. Margem de Sucesso: Sabor e qualidade.',
    clans: 'Todos',
    counterResist: 'N/A (ação de preparação)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Dar Primeiros Socorros',
    skill: 'Medicina',
    level: 'N/A',
    test: 'Raciocínio + Medicina',
    difSugest: '2 (ferimentos leves) / 4 (ferimentos graves/veneno)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Estabiliza/Alivia ferimentos. Margem de Sucesso: Rapidez da melhora/remoção de efeito.',
    clans: 'Todos',
    counterResist: 'N/A (ação de cura)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Persuadir/Convencer',
    skill: 'Persuasão',
    level: 'N/A',
    test: 'Carisma ou Manipulação + Persuasão',
    difSugest: '1 (simples) / 3 (opinião neutra) / 5 (opinião forte)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Alvo considera a proposta. Margem de Sucesso: Força do convencimento.',
    clans: 'Todos',
    counterResist:
      'Autocontrole + Persuasão (manter-se firme); FV (anular sucesso)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Intimidar/Amedrontar',
    skill: 'Intimidação',
    level: 'N/A',
    test: 'Força ou Carisma + Intimidação',
    difSugest: '2 (alvo fraco) / 4 (corajoso) / 6 (furioso)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Alvo intimidado. Margem de Sucesso: Profundidade do medo.',
    clans: 'Todos',
    counterResist:
      'Vigor + Determinação (resistir ao medo); Autocontrole + Intimidação (intimidar de volta)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Mentir/Enganar',
    skill: 'Manha',
    level: 'N/A',
    test: 'Manipulação + Manha',
    difSugest: '2 (simples) / 4 (detalhada) / 6 (evidência contrária)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Alvo acredita. Margem de Sucesso: Credibilidade/duração.',
    clans: 'Todos',
    counterResist:
      'Raciocínio + Investigação/Empatia (perceber falhas); Auspícios (ver auras/ilusões)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Hackear Computador',
    skill: 'Tecnologia',
    level: 'N/A',
    test: 'Inteligência + Tecnologia',
    difSugest: '2 (antigo) / 4 (básico) / 6 (criptografado)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Obtém acesso/informação. Margem de Sucesso: Profundidade/rapidez.',
    clans: 'Todos',
    counterResist: 'Inteligência + Segurança (programas de defesa)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Pesquisar Livros/Arquivos',
    skill: 'Investigação ou Erudição',
    level: 'N/A',
    test: 'Inteligência + Investigação ou Erudição',
    difSugest: '1 (comum) / 3 (obscura) / 5 (rara)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Encontra informação. Margem de Sucesso: Rapidez/detalhes.',
    clans: 'Todos',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Pensar Rápido/Resolver Problema',
    skill: 'Inteligência (geral)',
    level: 'N/A',
    test: 'Raciocínio + Inteligência',
    difSugest: '2 (simples) / 4 (desafiador) / 6 (complexo)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Encontra uma solução/percepção. Margem de Sucesso: Rapidez/completude.',
    clans: 'Todos',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Analisar um Crime/Cena',
    skill: 'Investigação',
    level: 'N/A',
    test: 'Raciocínio + Investigação',
    difSugest: '2 (óbvio) / 4 (comum) / 6 (oculto)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Encontra pistas. Margem de Sucesso: Quantidade/relevância.',
    clans: 'Todos',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Tentar Disfarce',
    skill: 'Etiqueta ou Manha',
    level: 'N/A',
    test: 'Manipulação + Etiqueta ou Manha',
    difSugest: '2 (multidão) / 4 (conhecidos) / 6 (inimigos)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description:
      'Cria um disfarce convincente. Margem de Sucesso: Qualidade/duração.',
    clans: 'Todos',
    counterResist:
      'Raciocínio + Prontidão/Empatia (notar algo estranho); Auspícios (ver através de ilusões)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Coletar Informação (Boatos)',
    skill: 'Manha',
    level: 'N/A',
    test: 'Carisma ou Manipulação + Manha',
    difSugest: '1 (fácil) / 3 (desafiador) / 5 (difícil/perigoso)',
    costs: 'N/A',
    bloodPotency: 'Afeta Fome da rolagem',
    description: 'Obtém boatos. Margem de Sucesso: Qualidade/veracidade.',
    clans: 'Todos',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Sentir Presenças Sobrenaturais',
    skill: 'Auspícios',
    level: 1,
    test: 'Raciocínio + Prontidão',
    difSugest: '1 (forte)/2 (fraca)/3 (oculta)',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Percepção de auras, presença da Besta, magia.',
    clans: 'Malkavianos, Tremere, Hecata',
    counterResist: 'Ofuscação (esconder a presença sobrenatural)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Obter Premonições',
    skill: 'Auspícios',
    level: 2,
    test: 'Raciocínio + Auspícios',
    difSugest: '3 (clara)/5 (obscura)/7 (perigosa)',
    costs: '1 PB',
    bloodPotency: 'N/A',
    description:
      'Visões do futuro ou do passado imediato, concedendo bônus/pistas.',
    clans: 'Malkavianos, Tremere, Hecata',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Ver Através de Ilusões',
    skill: 'Auspícios',
    level: 3,
    test: 'Raciocínio + Auspícios',
    difSugest: 'DIF da ilusão',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Revela a verdadeira natureza de objetos ou pessoas iludidas.',
    clans: 'Malkavianos, Tremere, Hecata',
    counterResist: 'N/A (a ilusão é o contra-ataque)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'A Visão da Aura',
    skill: 'Auspícios',
    level: 4,
    test: 'Raciocínio + Auspícios',
    difSugest: '1 (simples)/3 (complexa)',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Revela auras, estados de saúde e emoção de seres vivos.',
    clans: 'Malkavianos, Tremere, Hecata',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Clarividência',
    skill: 'Auspícios',
    level: 5,
    test: 'Raciocínio + Auspícios',
    difSugest: '4 (próximo)/6 (distante)',
    costs: '1 PB',
    bloodPotency: 'N/A',
    description: 'Permite ver e ouvir em locais distantes.',
    clans: 'Malkavianos, Tremere, Hecata',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Sentir a Besta',
    skill: 'Animalismo',
    level: 1,
    test: 'Raciocínio + Animalismo',
    difSugest: '1-3',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description:
      'Percepção do estado emocional de animais ou da Besta em vampiros.',
    clans: 'Gangrel, Nosferatu',
    counterResist:
      'Autocontrole + Subterfúgio (para vampiro tentar esconder sua Besta)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Comunicação com Animais',
    skill: 'Animalismo',
    level: 2,
    test: 'Carisma + Animalismo',
    difSugest: '1-3 (complexidade)',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Entender e ser entendido por animais.',
    clans: 'Gangrel, Nosferatu',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Domar a Besta',
    skill: 'Animalismo',
    level: 3,
    test: 'Manipulação + Animalismo',
    difSugest: '2-4',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description:
      'Força um animal a obedecer sua vontade, ou acalma um animal selvagem.',
    clans: 'Gangrel, Nosferatu',
    counterResist: 'N/A (resistência é a natureza do animal)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Familiar',
    skill: 'Animalismo',
    level: 4,
    test: 'Determinação + Animalismo',
    difSugest: '3-5',
    costs: 'Gasto de PB e tempo',
    bloodPotency: 'N/A',
    description:
      'Cria um laço de sangue com um animal, tornando-o um servo leal.',
    clans: 'Gangrel, Nosferatu',
    counterResist:
      'Matar o familiar (quebra o laço); Disciplinas de Dominação/Presença (contra o familiar ou o vampiro)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Coração de Fera',
    skill: 'Animalismo',
    level: 5,
    test: 'N/A (ativado)',
    difSugest: 'N/A',
    costs: 'Gasto de PB',
    bloodPotency: 'N/A',
    description:
      'Transforma temporariamente em um híbrido homem-fera (concede bônus físicos).',
    clans: 'Gangrel',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Mesmerize',
    skill: 'Dominação',
    level: 1,
    test: 'Manipulação + Dominação',
    difSugest: 'vs. FV do alvo',
    costs: 'N/A',
    bloodPotency: 'Alvo com PB > seu: +1 DIF.',
    description: 'Força o alvo a seguir uma ordem verbal simples.',
    clans: 'Ventrue, Tremere, Lasombra',
    counterResist: 'Força de Vontade (resistir); Convicções',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Manipular Memórias',
    skill: 'Dominação',
    level: 2,
    test: 'Manipulação + Dominação',
    difSugest: 'vs. FV do alvo',
    costs: 'N/A',
    bloodPotency: 'Alvo com PB > seu: +1 DIF.',
    description: 'Apaga ou altera memórias.',
    clans: 'Ventrue, Tremere, Lasombra',
    counterResist: 'Força de Vontade (resistir); Convicções',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Comandar a Lealdade (Massa)',
    skill: 'Dominação',
    level: 4,
    test: 'Carisma + Dominação',
    difSugest: 'vs. FV do grupo (média)',
    costs: 'N/A',
    bloodPotency: 'Alvo com PB > seu: +1 DIF.',
    description: 'Força um grupo a seguir ordens complexas.',
    clans: 'Ventrue, Tremere, Lasombra',
    counterResist: 'Força de Vontade (resistência individual)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Possessão Corporal',
    skill: 'Dominação',
    level: 5,
    test: 'Manipulação + Dominação',
    difSugest: 'vs. FV do alvo',
    costs: '1 PB/cena',
    bloodPotency: 'Alvo com PB > seu: +1 DIF.',
    description: 'Assume o controle completo do corpo de outro.',
    clans: 'Ventrue, Tremere, Lasombra',
    counterResist:
      'Força de Vontade Extrema (do alvo); Disciplinas de Autocontrole',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Dementation',
    skill: 'Demência',
    level: 1,
    test: 'Manipulação + Demência',
    difSugest: 'vs. Vigor + Determinação',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Causa medo, paranoia ou loucura temporária no alvo.',
    clans: 'Malkavianos',
    counterResist:
      'Força de Vontade (ignorar o efeito por um turno/cena); Autocontrole + Força de Vontade (superar a aflição)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Insight Louco',
    skill: 'Demência',
    level: 2,
    test: 'Manipulação + Demência',
    difSugest: 'vs. Autocontrole + Determinação',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Acelera as Compulsões de um alvo, ou aprofunda sua loucura.',
    clans: 'Malkavianos',
    counterResist: 'Autocontrole + Determinação (resistir)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Delírio Perigoso',
    skill: 'Demência',
    level: 3,
    test: 'Manipulação + Demência',
    difSugest: '3-5 (complexidade)',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description:
      'Cria ilusões complexas e aterrorizantes que afetam múltiplos sentidos.',
    clans: 'Malkavianos',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Sementes da Loucura',
    skill: 'Demência',
    level: 4,
    test: 'Manipulação + Demência',
    difSugest: '6+',
    costs: 'Gasto de PB',
    bloodPotency: 'N/A',
    description: 'Instila uma loucura permanente no alvo.',
    clans: 'Malkavianos',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Visão Partilhada',
    skill: 'Demência',
    level: 5,
    test: 'N/A (ativado)',
    difSugest: 'N/A',
    costs: 'Gasto de PB',
    bloodPotency: 'N/A',
    description: 'Compartilha sua própria insanidade com outros.',
    clans: 'Malkavianos',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Ignis Fatuus',
    skill: 'Quimerismo',
    level: 1,
    test: 'Manipulação + Quimerismo',
    difSugest: '1-3',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Cria uma pequena ilusão simples (sons, cheiros, objetos).',
    clans: 'Ministry',
    counterResist:
      'Raciocínio + Prontidão (perceber inconsistências); Auspícios (ver a aura da ilusão)',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Máscara da Besta',
    skill: 'Quimerismo',
    level: 2,
    test: 'Carisma + Quimerismo',
    difSugest: '2-4',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Muda a aparência do vampiro para causar terror ou fascínio.',
    clans: 'Ministry',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Delírio Horrível',
    skill: 'Quimerismo',
    level: 3,
    test: 'Manipulação + Quimerismo',
    difSugest: '3-5',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description:
      'Cria ilusões complexas e multissensoriais para um único alvo.',
    clans: 'Ministry',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Alucinações da Mente',
    skill: 'Quimerismo',
    level: 4,
    test: 'Manipulação + Quimerismo',
    difSugest: '4-6',
    costs: 'N/A',
    bloodPotency: 'N/A',
    description: 'Causa alucinações em um grupo de pessoas.',
    clans: 'Ministry',
    counterResist: 'N/A',
  },
  {
    cover: PlaceholderImg,
    actionPower: 'Projeção de Pesadelos',
    skill: 'Quimerismo',
    level: 5,
    test: 'Manipulação + Quimerismo',
    difSugest: '6+',
    costs: 'Gasto de PB',
    bloodPotency: 'N/A',
    description: 'Traz os pesadelos do alvo à vida.',
    clans: 'Ministry',
    counterResist: 'N/A',
  },
];

export const powerData = rawPowerData.map((item, index) => ({
  id: String(index + 1).padStart(3, '0'),
  ...item,
}));
